baseurl: "http://fossday.org"
title: "Primeiro Foss Day Lajeado"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "FossDay Pelotas"
  Description: "Primeiro evento FOSS Day Pelotas. Participação do ilustre \"Maddog\""
  Date: "12 de Maio de 2018"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Faculdade de Tecnologia Senac Pelotas"
  Address: "Rua Gonçalves Chaves, 602 - Centro, Pelotas"
  City:  "Pelotas"
  State: "Rio Grande do Sul"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "AIzaSyD0SXo4PtQAlft4ERHwSlsGjQ6RYyF20hc"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    # - sponsors
    # - support
    # - partners
    # - presenter

  # Titles which you can translate to other languages
  Titles:
    about: "Sobre"
    location: "Local"
    speakers: "Palestrantes"
    schedule: "Grade"


  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Faça seu registro!"
    link: "https://goo.gl/FWFy9A"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  ForkButton:
    repository: "https://github.com/fossday/site"


  # The entire schedule
  Schedule:
    - name: "Abertra"
      time: "08:00"

    - name: "Eduardo Monks"
      photo: "/img/speakers/eduardo_monks.png"
      bio: "Administrador de redes com experiência de mais de 20 anos (UCPEL, UFPEL). É docente do curso Superior em Tecnologia de Redes de Computadores (Faculdade de Tecnologia SENAC Pelotas). Possui certificações da área de redes e Linux."
      link:
        href: "http://www.youtube.com/emmonks"
        text: "http://www.youtube.com/emmonks"
      presentation:
        title: "Utilizando o emulador Common Open Research Emulator (CORE)"
        description: "Neste workshop, será apresentado o emulador Core Network Emulator, baseado em Linux/FreeBSD, e a exploração de cenários práticos na administração de redes"
        time: "08h30"

    - name: "Cesar Brod"
      photo: "/img/speakers/cesar_brod.jpg"
      bio: "Diretor de Desenvolvimento de Comunidades do Linux Professional Institute para a América Latina e Caribe, que reside em Lajeado no Rio Grande do Sul.
      Atua na área de informática desde 1982. Sua formação profissional deu-se em grande parte nos Estados Unidos, Canadá e França. Começou a trabalhar com o Linux em 1993 e, desde 1997 desenvolve, através da BrodTec, serviços de consultoria, gestão de projetos e criação de modelos de negócios que têm por base softwares de código aberto."
      link:
        href: "http://www.brod.com.br"
        text: "http://www.brod.com.br"
      presentation:
        title: "Qual será o trabalho?"
        description: ""
        time: "10h00"

    - name: "Jon \"Maddog\" Hall"
      photo: "/img/speakers/maddog.png"
      bio: "Jon \"Maddog\" Hall é o Diretor Executivo da Linux International, CEO da OptDyn e presidente do conselho do Linux Professional Institute. O apelido lhe foi dados por seus alunos na Hartford State Technical College, onde ele era Chefe do Departamento de Ciência da Computação. O próprio Hall afirma que o apelido “vem de um tempo em que eu tinha pouco controle sobre o meu temperamento”. Jon trabalha com informática desde 1969, trabalhou para a Western Electric Corporation, Aetna Life and Casualty, Bell Laboratories, Digital Equipment Corporation, VA Linux Systems, e SGI."
      company: "Diretor Executivo da Linux International, CEO da OptDyn e presidente do conselho do Linux Professional Institute."
      link:
        href: "http://twitter.com/maddoghall"
        text: "@maddoghall"
      presentation:
        title: "Seu futuro no mercado de trabalho com Linux e Software Livre"
        description: ""
        time: "11h00"
